### ISSUE TITLE
Presentation to-do list

### ISSUE THREAD

**Issue by matdehaven** [VFCI/vfciBusinessCycles#17]
- [x] Optimize matching all IRFs by shifting starting and ending frequencies (with a min and max frequency length). 
- [x] Also optimize by just targeting unemployment IRF, do we get the same one?
- [x] Evidence for there being two shocks within the Business cycle frequency? One of them related to VFCI, one not?
- [ ] Historical realized structural shocks for both unemployment and vfci targeting. Both a time series plot and a scatter plot between the two.
- [x] Plot the weights that each of the two structural shocks put on the reduced form shocks (as a bar graph, sorted high to low for unemployment target).
- [x] Compare the FEVDFD for each of the models.  Both in time and frequency domains.
- [x] Does removing the business cycle component from the VFCI shock leave a variable that does not explain much in the business cycle?
- [ ] Add credit-to-gdp as a variable to the VAR, add GZ spread as well as a variable (GZ is in the VFCI data)
- [ ] Scatter plot of the vfci shock with the monetary policy shock
- [ ] Run the main figure ending in 2007, ending in 2022

**Comment by matdehaven** [comment]
Closing this issue as the presentation is done.  Items I did not get to were given their own issues.
